name: 'check_phpstan_php'
description: 'github action template that check for php stan'
author: 'Anton Koshel <fxpw@outlook.com>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'eye'  
  color: 'gray-dark'